apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/cert-manager

patchesJson6902:

- path: ./patches/cert-manager.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    kind: HelmRelease
    namespace: cert-manager
    name: cert-manager
  