---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:

  releaseName: actions-runner-controller
  interval: 5m

  chart:
    spec:
      chart: actions-runner-controller
      sourceRef:
        kind: HelmRepository
        name: github-actions-runner
        namespace: flux-system
  install:
    remediation:
      retries: 3

  values:
    replicaCount: 2

    authSecret:
      enabled: true
      create: false
      name: controller-manager
      annotations: {}

    nodeSelector: {}

    tolerations: []

    affinity: {}

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    certManagerEnabled: true

    logFormat: json
