---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/stores
  - ../../base/secrets/github-actions-runner-app

patchesJson6902:

  - path: ./patches/stores/aws-secrets-manager.yaml
    target:
      group: external-secrets.io
      version: v1beta1
      kind: ClusterSecretStore
      namespace: external-secrets
      name: aws-secrets-manager

  - path: ./patches/secrets/github-actions-runner-app.yaml
    target:
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
      namespace: actions-runner-system
      name: github-actions-runner-app
