---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  interval: 5m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: metrics-server
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system

  # https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/values.yaml
  values:
    podDisruptionBudget:
      # https://kubernetes.io/docs/tasks/run-application/configure-pdb/
      enabled: false
      minAvailable: 1
