---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: configs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./configs/overlays/kind-local
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: sources