---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/metrics-server
  - ../../base/monitoring
  - ../../base/cert-manager
  - ../../base/external-secrets
  - ../../base/github-actions-runner

# patchesJson6902:

#   - path: ./patches/cert-manager.yaml
#     target:
#       group: helm.toolkit.fluxcd.io
#       version: v2beta1
#       kind: HelmRelease
#       namespace: cert-manager
#       name: cert-manager

#   - path: ./patches/external-secrets.yaml
#     target:
#       group: helm.toolkit.fluxcd.io
#       version: v2beta1
#       kind: HelmRelease
#       namespace: external-secrets
#       name: external-secrets

#   - path: ./patches/metrics-server.yaml
#     target:
#       group: helm.toolkit.fluxcd.io
#       version: v2beta1
#       kind: HelmRelease
#       namespace: kube-system
#       name: metrics-server
