---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-actions-runner-app
  namespace: actions-runner-system

spec:

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: controller-manager

  data:

    - secretKey: github_app_id
      remoteRef:
        # version: v1
        property: github_app_id_base64
        decodingStrategy: Base64

    - secretKey: github_app_installation_id
      remoteRef:
        # version: v1
        property: github_app_installation_id_base64
        decodingStrategy: Base64

    - secretKey: github_app_private_key
      remoteRef:
        # version: v1
        property: github_app_private_key_base64
        decodingStrategy: Base64
